In [1]:
%cd /content/drive/MyDrive/001_SUNNY_BHAVEEN_CHANDRA/001_My_Classes/FSDS_Feb_Batch/ALL_NOTES/June-05

/content/drive/MyDrive/001_SUNNY_BHAVEEN_CHANDRA/001_My_Classes/FSDS_Feb_Batch/ALL_NOTES/June-05


In [2]:
try:
  from aitextgen import aitextgen
except:
  print('intalling aitextgen...')
  !pip install aitextgen -q
  from aitextgen import aitextgen



intalling aitextgen...
     |████████████████████████████████| 572 kB 5.1 MB/s 
     |████████████████████████████████| 4.2 MB 43.2 MB/s 
     |████████████████████████████████| 87 kB 5.6 MB/s 
     |████████████████████████████████| 585 kB 42.8 MB/s 
     |████████████████████████████████| 596 kB 51.3 MB/s 
     |████████████████████████████████| 418 kB 54.5 MB/s 
     |████████████████████████████████| 140 kB 46.7 MB/s 
     |████████████████████████████████| 1.1 MB 34.1 MB/s 
     |████████████████████████████████| 6.6 MB 44.8 MB/s 
     |████████████████████████████████| 86 kB 5.0 MB/s 
     |████████████████████████████████| 144 kB 37.6 MB/s 
     |████████████████████████████████| 271 kB 44.9 MB/s 
     |████████████████████████████████| 94 kB 2.6 MB/s 


In [4]:
ai = aitextgen(tf_gpt2="124M", to_gpu=False)

In [5]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2022-06-05 12:20:01--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.06s   

2022-06-05 12:20:01 (18.1 MB/s) - ‘input.txt’ saved [1115394/1115394]



In [6]:
input_file = "input.txt"

In [7]:
ai.train(train_data=input_file)

  0%|          | 0/40000 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/callback_connector.py:152: LightningDeprecationWarning: Setting `Trainer(checkpoint_callback=False)` is deprecated in v1.5 and will be removed in v1.7. Please consider using `Trainer(enable_checkpointing=False)`.
  f"Setting `Trainer(checkpoint_callback={checkpoint_callback})` is deprecated in v1.5 and will "
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/callback_connector.py:97: LightningDeprecationWarning: Setting `Trainer(progress_bar_refresh_rate=20)` is deprecated in v1.5 and will be removed in v1.7. Please pass `pytorch_lightning.callbacks.progress.TQDMProgressBar` with `refresh_rate` directly to the Trainer's `callbacks` argument instead. Or, to disable the progress bar pass `enable_progress_bar = False` to the Trainer.
  f"Setting `Trainer(progress_bar_refresh_rate={progress_bar_refresh_rate})` is deprecated in v1.5 and"
/usr/local/lib/python3.7/dist-packages/pytorch_lightn

  0%|          | 0/5000 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:2282: LightningDeprecationWarning: `trainer.progress_bar_dict` is deprecated in v1.5 and will be removed in v1.7. Use `ProgressBarBase.get_metrics` instead.
  "`trainer.progress_bar_dict` is deprecated in v1.5 and will be removed in v1.7."
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py:726: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")


KeyboardInterrupt: ignored

In [8]:
import numpy as np

In [12]:
data = np.random.randint(0,100,25)
data

array([39, 64, 88,  5, 34, 11, 63,  8, 11, 34, 52, 33, 44,  3, 90, 68,  6,
       17, 68, 30, 56, 52, 84, 18, 13])

In [14]:
np.sort(data)[::-1]

array([90, 88, 84, 68, 68, 64, 63, 56, 52, 52, 44, 39, 34, 34, 33, 30, 18,
       17, 13, 11, 11,  8,  6,  5,  3])

In [16]:
def top_k(data, k=10):
  descending_data = np.sort(data)[::-1]
  return descending_data[:k]

In [17]:
def top_p(data, p=80):
  new = [d for d in data if d > p]
  return new

In [18]:
top_k(data, k =10)

array([90, 88, 84, 68, 68, 64, 63, 56, 52, 52])

In [19]:
top_p(data, p =80)

[88, 90, 84]